"""empty message

Revision ID: 2ccd5509840b
Revises: 
Create Date: 2020-04-28 15:16:28.459280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccd5509840b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('user', sa.String(length=80), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_agent', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.Boolean(), nullable=False),
    sa.Column('has_profile', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('withdrawal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('trxn_init_code', sa.String(length=30), nullable=False),
    sa.Column('trxn_amount', sa.Float(), nullable=False),
    sa.Column('trxn_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('agency_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('middle_name', sa.String(length=20), nullable=False),
    sa.Column('sir_name', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('next_of_kin_name', sa.String(length=50), nullable=False),
    sa.Column('next_of_kin_email', sa.String(length=50), nullable=False),
    sa.Column('next_of_kin_phone', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('next_of_kin_email'),
    sa.UniqueConstraint('next_of_kin_phone'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('trxn_code', sa.String(length=30), nullable=False),
    sa.Column('trxn_ai_key', sa.Integer(), nullable=False),
    sa.Column('trxn_tracking_id', sa.String(length=30), nullable=False),
    sa.Column('trxn_account', sa.String(length=30), nullable=False),
    sa.Column('trxn_amount', sa.Float(), nullable=False),
    sa.Column('trxn_type', sa.String(length=10), nullable=False),
    sa.Column('comm_code', sa.String(length=80), nullable=False),
    sa.Column('agent_code', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_code'], ['agency_code.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('trxn_ai_key'),
    sa.UniqueConstraint('trxn_code'),
    sa.UniqueConstraint('trxn_tracking_id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('trxn_init_code', sa.String(length=30), nullable=False),
    sa.Column('trxn_ai_key', sa.Integer(), nullable=False),
    sa.Column('trxn_tracking_id', sa.String(length=30), nullable=False),
    sa.Column('trxn_account', sa.String(length=30), nullable=False),
    sa.Column('trxn_amount', sa.Float(), nullable=False),
    sa.Column('trxn_type', sa.String(length=10), nullable=False),
    sa.Column('trxn_cr_amt', sa.Float(), nullable=False),
    sa.Column('trxn_dr_amt', sa.Float(), nullable=False),
    sa.Column('reducing_bal', sa.Float(), nullable=False),
    sa.Column('agency_comm_amt', sa.Float(), nullable=False),
    sa.Column('accu_comm_amt', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trxn_init_code'], ['referral.trxn_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('trxn_ai_key'),
    sa.UniqueConstraint('trxn_init_code'),
    sa.UniqueConstraint('trxn_tracking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('referral')
    op.drop_table('user_data')
    op.drop_table('agency_code')
    op.drop_table('withdrawal')
    op.drop_table('user')
    op.drop_table('otp')
    op.drop_table('commission')
    # ### end Alembic commands ###
